greenthumbsup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('plants/', views.plants_index, name='index'),
    path('plants/my_plants/', views.my_plants, name='my_plants'),
    path('plants/my_plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
    path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
    path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
    path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
    path('plants/<int:plant_id>/add_photo/', views.add_photo, name='add_photo'),
    path('plants/<int:plant_id>/assoc_fertilizer/<int:fertilizer_id>/', views.assoc_fertilizer, name='assoc_fertilizer'),
    path('plants/<int:plant_id>/unassoc_fertilizer/<int:fertilizer_id>/', views.unassoc_fertilizer, name='unassoc_fertilizer'),
    path('fertilizers/', views.FertilizerList.as_view(), name='fertilizers_index'),
    path('fertilizers/<int:pk>/', views.FertilizerDetail.as_view(), name='fertilizers_detail'),
    path('fertilizers/create/', views.FertilizerCreate.as_view(), name='fertilizers_create'),
    path('fertilizers/<int:pk>/update/', views.FertilizerUpdate.as_view(), name='fertilizers_update'),
    path('fertilizers/<int:pk>/delete/', views.FertilizerDelete.as_view(), name='fertilizers_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

import logging
logging.basicConfig(level=logging.DEBUG)

TIME_OF_DAY_CHOICES = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)

class Fertilizer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('fertilizers_detail', kwargs={'pk':self.id})

class Plant(models.Model):
    name = models.CharField(max_length=100)
    plant_type = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    sunlight = models.CharField(max_length=100)
    adoption_date = models.DateField('Adoption Date')
    notes = models.TextField(max_length=250, blank=True)
    fertilizers = models.ManyToManyField(Fertilizer, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for plant_id: {self.plant_id} @{self.url}"

class Watering(models.Model):
    date = models.DateField('Watering Date')
    time = models.CharField(
        'Time of Day',
        max_length=1,
        choices=TIME_OF_DAY_CHOICES,
        default=TIME_OF_DAY_CHOICES[0][0]
    )
    frequency = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.get_time_display()} on {self.date}"
    
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
    class Meta:
        model = Watering
        fields = ['date', 'time', 'frequency']

main_app/views.py
import os, uuid, boto3
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Plant, Fertilizer, Photo
from .forms import WateringForm 

import logging
logging.basicConfig(level=logging.DEBUG)

def home(request):
    """
    home view
    http://localhost:8000/
    """
    photos = Photo.objects.all()
    return render(request, 'home.html', {'photos': photos})

def about(request):
    """
    about view
    http://localhost:8000/about/
    """
    return render(request, 'about.html')

def plants_index(request):
    """
    plants index page
    http://localhost:8000/plants/
    """
    plants = Plant.objects.all()
    return render(request, 'plants/index.html', {'plants': plants})

@login_required
def my_plants(request):
    """
    user's plants index page
    http://localhost:8000/plants/my_plants/
    """
    plants = Plant.objects.filter(user=request.user)
    return render(request, 'plants/my_plants.html', {'plants': plants})

@login_required
def plants_detail(request, plant_id):
    """
    plant detail page
    http://localhost:8000/dogs/1/
    """
    try:
        plant = Plant.objects.get(id=plant_id)
        fertilizers_plant_doesnt_have = Fertilizer.objects.exclude(id__in = plant.fertilizers.all().values_list('id'))
        return render(request, 'plants/detail.html', {
            'plant': plant, 
            'watering_form': WateringForm,
            'fertilizers': fertilizers_plant_doesnt_have
            })
    except Plant.DoesNotExist:
        return render(request, 'errorpage.html')

class PlantCreate(LoginRequiredMixin, CreateView):
    """
    This class will create a plant object
    http://localhost:8000/plants/create/
    """
    model = Plant
    fields = ['name', 'plant_type', 'color', 'sunlight', 'adoption_date', 'notes']
    success_url = '/plants/my_plants/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
    """
    This class will update a plant object from the DB
    http://localhost:8000/plants/1/update/
    """
    model = Plant
    fields = ['name', 'plant_type', 'color', 'sunlight', 'adoption_date', 'notes']
    
    def get_success_url(self, **kwargs):
        return reverse('detail', args=(self.object.id,))

class PlantDelete(LoginRequiredMixin, DeleteView):
    """
    This class will delete a plant object from the DB
    http://localhost:8000/plants/1/delete/
    """
    model = Plant
    success_url = '/plants/my_plants/'

@login_required
def add_watering(request, plant_id):
    form = WateringForm(request.POST)
    if form.is_valid():
        new_watering = form.save(commit=False)
        new_watering.plant_id = plant_id
        new_watering.save()
    return redirect('detail', plant_id=plant_id)

@login_required
def add_photo(request, plant_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, plant_id=plant_id)
        except:
            print('An error occurred while uploading file to S3')
    return redirect('detail', plant_id=plant_id)

@login_required
def assoc_fertilizer(request, plant_id, fertilizer_id):
    Plant.objects.get(id=plant_id).fertilizers.add(fertilizer_id)
    return redirect('detail', plant_id=plant_id)

@login_required
def unassoc_fertilizer(request, plant_id, fertilizer_id):
    Plant.objects.get(id=plant_id).fertilizers.remove(fertilizer_id)
    return redirect('detail', plant_id=plant_id)

def signup(request):
    """
    signup page
    http://localhost:8000/accounts/signup/
    """
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up, please try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class FertilizerList(LoginRequiredMixin, ListView):
    """
    fertilizer index page
    http://localhost:8000/fertilizers/
    """
    model = Fertilizer

class FertilizerDetail(LoginRequiredMixin, DetailView):
    """
    fertilizer detail page
    http://localhost:8000/fertilizers/1/
    """
    model = Fertilizer

class FertilizerCreate(LoginRequiredMixin, CreateView):
    """
    This class will create a fertilizer object
    http://localhost:8000/fertilizers/create/
    """
    model = Fertilizer
    fields = '__all__'
    success_url = '/fertilizers/'

class FertilizerUpdate(LoginRequiredMixin, UpdateView):
    """
    This class will update a fertilizer object
    http://localhost:8000/fertilizers/1/update/
    """
    model = Fertilizer
    fields = '__all__'

class FertilizerDelete(LoginRequiredMixin, DeleteView):
    """
    This class will delete a fertilizer object
    http://localhost:8000/fertilizers/1/delete/
    """
    model = Fertilizer
    success_url = '/fertilizers/'

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center-align" style="color: #6d4c41; font-weight: 900; font-family: 'Italiana', serif;">Plant Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content" style="background-color: #FFFDE7">
                <span class="card-title" style="color: #0288d1; font-size: 2em; font-weight: 900; font-family: 'Italiana', serif;">{{ plant.name }}</span>
                <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Plant Type: {{ plant.plant_type }}</p>
                <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Color: {{ plant.color }}</p>
                <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Sunlight: {{ plant.sunlight }}</p>
                <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Adoption Date: {{ plant.adoption_date }}</p>
                <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Notes: {{ plant.notes }}</p>
            </div>
            {% if user == plant.user %}
                <div class="card-action">
                    <a class="btn-floating waves-effect waves-light orange" href="{% url 'plants_update' plant.id %}"><i class="material-icons">edit</i></a>
                    <span style="font-weight: 900; font-family: 'Italiana', serif;">EDIT</span>
                    <a class="btn-floating waves-effect waves-light red" href="{% url 'plants_delete' plant.id %}" class="red-text"><i class="material-icons">delete</i></a>
                    <span style="font-weight: 900; font-family: 'Italiana', serif;">DELETE</span>
                </div>
            {% else %}
                <div class="card-action">
                    <p style="font-family: 'Roboto', sans-serif;">View Only</p>
                </div>
            {% endif %}
        </div>
        {% for photo in plant.photo_set.all %}
            <img class="responsive-img card-panel" src="{{photo.url}}" style="white-space: nowrap;">
        {% empty %}
            <div class="card-panel teal-text center-align" style="font-size: 1.5em; font-weight: 900; font-family: 'Italiana', serif;">No Photos Uploaded</div>
        {% endfor %}

        <div class="card">
            <div class="card-content" style="background-color: #FFFDE7">
                {% if user == plant.user %}
                    <form action="{% url 'add_photo' plant.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
                        {% csrf_token %}
                        <input type="file" name="photo-file">
                        <br><br>
                        <button class="waves-effect waves-light btn" style="font-weight: 900; font-family: 'Italiana', serif;"><i class="material-icons right">file_upload</i>UPLOAD</button>
                    </form>
                {% else %}
                
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col s6">
        {% if user == plant.user %}
            <form method="post" action="{% url 'add_watering' plant.id %}">
                {% csrf_token %}
                {{ watering_form.as_p }}
                <button type="submit" class="btn-floating waves-effect waves-light light-blue darken-2"><i class="material-icons">water_drop</i></button>
                <span style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">WATER</span>
            </form>
        {% else %}
        
        {% endif %}
            <br>
            <table class="responsive-table">
                <thead>
                    <tr>
                        <th style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">Date</th>
                        <th style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">Time</th>
                        <th style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">Frequency</th>
                    </tr>
                </thead>
                <tbody>
                    {% for watering in plant.watering_set.all %}
                        <tr>
                            <td style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">{{watering.date}}</td>
                            <td style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">{{watering.get_time_display}}</td>
                            <td style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">{{watering.frequency}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        {% if user == plant.user %}
            <h3 class="purple-text" style="font-weight: 900; font-family: 'Italiana', serif;">{{ plant.name }}'s Fertilizers</h3>
            {% if plant.fertilizers.count %}
                {% for fertilizer in plant.fertilizers.all %}
                    <div class="card">
                        <div class="card-content" style="background-color: #FFFDE7">
                            <span class="card-title">
                                <span style="font-family: 'Italiana', serif;">{{ fertilizer.name }}</span> 
                            </span>
                        </div>
                        <div class="card-action">
                            <form action="{% url 'unassoc_fertilizer' plant.id fertilizer.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn-floating waves-effect waves-light red"><i class="material-icons right">remove_circle_outline</i></button>
                                <span style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">REMOVE</span>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5 class="cyan-text" style="font-size: 2em; font-weight: 900; font-family: 'Italiana', serif;">No Fertilizer<i class="material-icons left">sentiment_dissatisfied</i>s</h5>
            {% endif %}
        {% else %}
    
        {% endif %}

    </div>
    <!-- Available fertilizers will come after this line -->
    <div class="col s6">
        {% if user == plant.user %}
            <h3 class="deep-purple-text" style="font-weight: 900; font-family: 'Italiana', serif;">Available Fertilizers</h3>
            {% if fertilizers.count %}
                {% for fertilizer in fertilizers.all %}
                    <div class="card">
                        <div class="card-content" style="background-color: #FFFDE7">
                            <span class="card-title">
                                <span style="font-size: 1.2em; font-weight: 900; font-family: 'Italiana', serif;">{{ fertilizer.name }}</span>
                            </span>
                        </div>
                        <div class="card-action">
                            <form action="{% url 'assoc_fertilizer' plant.id fertilizer.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn" style="font-size: 1.2em; font-weight: 900; font-family: 'Italiana', serif;">Add</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5 style="font-weight: 900; font-family: 'Italiana', serif;">{{plant.name}} Already Has All Fertilizers Available</h5>
            {% endif %}
        {% else %}
    
        {% endif %}
    </div>
</div>

<script>

    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const fertDateEl = document.getElementById('id_fertilize_date');
    M.Datepicker.init(fertDateEl, {
        format: 'yyyy-mm-dd',
        autoClose: true
    });

    const selectEl = document.getElementById('id_time');
    M.FormSelect.init(selectEl);
    
</script>

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center-align" style="color: #6d4c41; font-weight: 900; font-family: 'Italiana', serif;">All Community Plants</h1>

<div class="container">
    <div class="row">
        {% for plant in plants %}
            <div class="col s12 m6 l4">
                <div class="card large" style="background-color: #FFFDE7; color: #0288d1">
                    <div class="card-content">
                        {% for photo in plant.photo_set.all %}
                            <img class="responsive-img card-panel" src="{{photo.url}}" style="white-space: nowrap;">
                        {% empty %}
                            <div class="card-panel teal-text center-align" style="font-size: 1.5em; font-weight: 900; font-family: 'Italiana', serif;">No Photos Uploaded</div>
                        {% endfor %}
                        <span class="card-title activator" style="font-size: 2em; font-weight: 900; font-family: 'Italiana', serif;">{{ plant.name }}
                            <i class="material-icons right">more_vert</i>
                        </span>
                        <p><a href="#">This is a link</a></p>
                    </div>
                    <div class="card-reveal" style="background-color: #FFFDE7; color: #0288d1">
                        <span class="card-title activator" style="font-size: 2em; font-weight: 900; font-family: 'Italiana', serif;">{{ plant.name }}
                            <i class="material-icons right">close</i>
                        </span>
                        <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Plant Type: {{ plant.plant_type }}</p>
                        <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Color: {{ plant.color }}</p>
                        <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Sunlight: {{ plant.sunlight }}</p>
                        <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Adoption Date: {{ plant.adoption_date }}</p>
                        <p style="font-size: 1.3em; font-weight: 900; font-family: 'Roboto', sans-serif;">Notes: {{ plant.notes }}</p>
                        {% if plant.user != user %}
                            <p style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', sans-serif;">Contributed by {{ plant.user }}</p>
                        {% else %}
                            <p style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">Green Thumbs Up!</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/plants/my_plants.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center-align" style="color: #6d4c41; font-weight: 900; font-family: 'Italiana', serif;">My Plants</h1>

<div class="container">
    <div class="row">
        {% if user %}
            {% for plant in plants %}
                <div class="col s12 m6 l4">
                    <a href="{% url 'detail' plant.id %}">
                        <div class="card large hoverable" style="background-color: #FFFDE7">
                            <div class="card-content">
                                <span class="card-title" style="font-size: 2em; font-weight: 900; font-family: 'Italiana', serif;">{{ plant.name }}</span>
                                {% for photo in plant.photo_set.all %}
                                    <img class="responsive-img card-panel" src="{{photo.url}}" style="white-space: nowrap;">
                                {% empty %}
                                    <div class="card-panel teal-text center-align" style="font-size: 1.3em; font-weight: 900; font-family: 'Italiana', serif;">No Photos Uploaded</div>
                                {% endfor %}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <center style="margin-top: 5vmin;">
                <lottie-player src="https://assets10.lottiefiles.com/private_files/lf30_uMKwX0.json"  
                    background="transparent"  
                    speed="1"  
                    style="width: 300px; height: 300px;"  
                    loop autoplay>
                </lottie-player>
                <h3 class="center-align" style="color: #6d4c41;">You Have No PLants Yet! Please Add A Plant</h3>
            </center>
        {% endif %}
    </div>
</div>

{% endblock %}